### ISSUE TITLE
allow mut

### ISSUE THREAD

**Issue by jvenant** [lerouxrgd/rsgen-avro#14]
Maybe it could be a good idea to add
```rust
#[allow(unused_mut)]
```
at the begining of the file 
To prevent some warnings on collections ?

**Comment by lerouxrgd** [comment]
Do you happen to have an example where this would help ?

**Comment by lerouxrgd** [comment]
Thank you for the example, it is fixed in `0.9.2`.

>no default converted to a None Option

Actually `None` is only for union type where first value is null, this is the standard in Avro. So no default is converted to an empty `HashMap`.

**Comment by jvenant** [comment]
You're absolutely right for None.
Thank you very much !

**Comment by lerouxrgd** [comment]
Closing this as the issue should be solved.
