### ISSUE TITLE
Panic index out of range

### ISSUE THREAD

**Issue by joonnna** [lerouxrgd/rsgen-avro#15]
Encountering a panic on the following line, should perhaps the index be `0` as the length is 1?
https://github.com/lerouxrgd/rsgen-avro/blob/716d0d230cbad6f448f2c3f7f512adce06f98e4c/src/templates.rs#L1124

I have a rather large Avro schema and having trouble pin-pointing exactly which field is producing this behaviour.

**Comment by lerouxrgd** [comment]
You're right, I will fix it soon.

However this branch is reached only if your field is of type `["null"]` which is weird at the first place. So maybe the panic is coming from somewhere else ?

**Comment by lerouxrgd** [comment]
I pushed a fix on master branch, could you please give it a try and let me know how it goes ?

**Comment by joonnna** [comment]
Thanks! It works!
The Avro schema I'm using seems to have multiple instances of `["some-type"]` which I think is a union of a single field? (which I agree is really odd, but sadly I do not control the definition of these schemas).

The output type for these fields are named `UnionMyType` which when replaced with `MyType` compiles and works!

Example: ["string"] results in the following output: 
```
`struct MyStruct {
     my_field: UnionString
}
```

**Comment by lerouxrgd** [comment]
Yeah usually you would have something like `["string", "int"]` which is an "unnamed union" which generates an enum named `UnionStringInt` with two variants `UnionStringInt::String(String)` and `UnionStringInt::Int(i32)`.

So unless you change the schema you will always get this wrapping `Union*` enum even though there is only one value in your union.

**Comment by lerouxrgd** [comment]
I released the fix in `0.9.3`.
