### ISSUE TITLE
Optionally generate builders for generated structs

### ISSUE THREAD

**Issue by gudjonragnar** [lerouxrgd/rsgen-avro#20]
I think it could be a great addition to the project to add the option to generate or derive builders for the generated structs, for example using this crate: https://github.com/colin-kiegel/rust-derive-builder.

**Comment by lerouxrgd** [comment]
Sure, it could be a `--derive-builder` like there is `--variant-access`.
Let me know if you want to do a PR for that, otherwise I can give it a try.

**Comment by gudjonragnar** [comment]
I created a PR, not sure if it is sufficient but please take a look.

**Comment by lerouxrgd** [comment]
Released in `0.9.7`.
