### ISSUE TITLE
Remove Default trait for whole structure

### ISSUE THREAD

**Issue by SneakyBerry** [lerouxrgd/rsgen-avro#27]
My suggestion is to use [field default](https://serde.rs/attr-default.html) for fields that provides default in avro schema instead implement default for whole structure.
I need to check required fields during deserailaztion instead get all fields filled by default values.

**Comment by SneakyBerry** [comment]
Should be resolved by [!28](https://github.com/lerouxrgd/rsgen-avro/pull/28)

**Comment by lerouxrgd** [comment]
Thanks for the PR ! I'll try to release it this weekend.

**Comment by SneakyBerry** [comment]
I found some corner case, if you set default value of nested record it will not compile if this record did not implements trait Default cos in your realisation it creates default object and then mutate it with some values. I think we can create an issue for it.

**Comment by lerouxrgd** [comment]
Do you have a small example with this corner case ?

**Comment by SneakyBerry** [comment]
Yes.
```json
{
  "type": "record",
  "name": "User",
  "fields": [
    {
      "name": "nested",
      "type": "record",
      "fields": [
        {
          "name": "a",
          "type": "int"
        },
        {
          "name": "b",
          "type": "int"
        }
      ],
      "default": {
        "a": 10
      }
    }
  ]
}
```
It generates this 
```rust
#[derive(Debug, PartialEq, Clone, serde::Deserialize, serde::Serialize)]
pub struct Nested {
    pub a: i32,
    pub b: i32,
}

#[derive(Debug, PartialEq, Clone, serde::Deserialize, serde::Serialize)]
#[serde(default)]
pub struct User {
    pub nested: Nested,
}

fn default_user_nested() -> Nested {
    {
        let mut r = Nested::default();
        r.a = 10;
        r
    }
}

impl Default for User {
    fn default() -> User {
        User {
            nested: default_user_nested(),
        }
    }
}
```

But `Default` is not implemented for `Nested`

**Comment by lerouxrgd** [comment]
Actually this is not a valid schema (checked with `avro-tools`), the valid version would be:

```json
{
  "type": "record",
  "name": "User",
  "fields": [ {
    "name": "nested",
    "type": {
      "type": "record",
      "name": "Nested",
      "fields": [ {
        "name": "a",
        "type": "int"
      }, {
        "name": "b",
        "type": "int"
      } ]
    },
    "default": {
        "a": 10,
        "b": 42
    }
  } ]
}

```

Note that `"b"` is actually required in `"default"` by the Avro spec.

Therefore a fix would be to generate:

```rs
fn default_user_nested() -> Nested { Nested { a: 10, b: 42 } }
```

**Comment by lerouxrgd** [comment]
I pushed a fix for it, let me know if that solves your corner case.

**Comment by SneakyBerry** [comment]
I expect an error, but ok.
I found new one:
```json
{
  "type": "record",
  "name": "User",
  "fields": [
    {
      "name": "nested",
      "type": "record",
      "fields": [
        {
          "name": "a",
          "type": "int"
        },
        {
          "name": "b",
          "type": "int",
          "default": 20
        }
      ],
      "default": {
        "a": 10
      }
    }
  ]
}
```
If it is valid avro schema then generated file is incorrect.
```rust
#[derive(Debug, PartialEq, Clone, serde::Deserialize, serde::Serialize)]
pub struct Nested {
    pub a: i32,
    #[serde(default = "default_nested_b")]
    pub b: i32,
}

fn default_nested_b() -> i32 {
    20
}

#[derive(Debug, PartialEq, Clone, serde::Deserialize, serde::Serialize)]
#[serde(default)]
pub struct User {
    pub nested: Nested,
}

fn default_user_nested() -> Nested {
    Nested { a: 10 }  // need to call default_nested_b()
}

impl Default for User {
    fn default() -> User {
        User {
            nested: default_user_nested(),
        }
    }
}
```
I'll try to fix it, add an error if defaults in record is incorrect and make PR.

**Comment by lerouxrgd** [comment]
> I expect an error, but ok.

Yes I am relying on `avro-rs` to parse schema and it doesn't throw an error in this case ... Maybe the new official avro crate will be better at parsing schemas.

> I found new one

Indeed it's another corner case

**Comment by lerouxrgd** [comment]
I pushed another a fix for it, let me know if it looks good to you.

**Comment by SneakyBerry** [comment]
It is not work on something like that.

```rust
let json_str = r#"
    {
      "nested": {
      }
    }
"#;
serde_json::from_str::<User>(json_str).unwrap()
```

```
Error("missing field `a`", line: 4, column: 11)
```

**Comment by lerouxrgd** [comment]
With `#[serde(default)]` logic this example can work only if `"nested"` is completely missing (and not just partially defined), or if all fields in `Nested` have a default value (in this case `"a"` doesn't have one, and therefore `Nested` is not `#[serde(default)]`).

**Comment by SneakyBerry** [comment]
Ok. Looks good!
