### ISSUE TITLE
Struct ordering

### ISSUE THREAD

**Issue by Pritesh-Patel** [lerouxrgd/rsgen-avro#3]
Just started using this, its great but because of this issue: https://github.com/flavray/avro-rs/issues/47 i have had to manually reorder the fields in the generated struct. Would it be possible to maintain the ordering in the schema in the struct also?

**Comment by lerouxrgd** [comment]
Hi, thank you for your feedback. I released a patch to preserve Avro records fields ordering in the generated Rust struct. Please give latest version (the `0.4.0`) a try and let me know if it works.

**Comment by Pritesh-Patel** [comment]
This worked great thanks! @lerouxrgd
