### ISSUE TITLE
Glob pattern generates Invalid arguments.

### ISSUE THREAD

**Issue by untereiner** [lerouxrgd/rsgen-avro#43]
When using the cli with multiple avsc files like: `rsgen-avro my/schemas/**/*.avsc test.rs`.
It generates a space separated list of files and I think the last argument as output file is missing.
I guess adding a flag instead of using the last argument could help.

**Comment by lerouxrgd** [comment]
Hmm can you try `rsgen-avro 'my/schemas/**/*.avsc' test.rs` ?
But I agree we shouldn't need extra quotes.

**Comment by untereiner** [comment]
yes it works with single quotes.
I noticed that docopt is [unmaintained]( https://github.com/docopt/docopt.rs#this-crate-is-unmaintained).
They suggest to use clap instead.

**Comment by lerouxrgd** [comment]
The same issue will happen with clap.
The problem is that the wildcard is interpreted in the terminal (by bash or so) before being passed as a program argument.

**Comment by untereiner** [comment]
ok a solution would be to a flag for the output file and let the list of files in the argument list for the *.avsc files
