### ISSUE TITLE
rsgen-avro throws error when --nullable param is used.

### ISSUE THREAD

**Issue by markfarnan** [lerouxrgd/rsgen-avro#45]
Problem:  

rsgen-avro throws error **"Templating error: Failed to render 'record.tera'"** when --nullable is used

Replication Steps:

1. Put the two files (attached below in the zip) in the same directory
2. run:  rsgen-avro --nullable "*.avsc" schema.rs

Note: removing --nullable, and no error is thrown.

[Archive.zip](https://github.com/lerouxrgd/rsgen-avro/files/10143437/Archive.zip)

**Comment by lerouxrgd** [comment]
Using `--nullable` requires all the fields to have a default value (which will be used when deserializing a null value).

In your example the fields for the record `ErrorInfo` don't have default values, hence the error.

With the following schema, your example  works fine:
```json
{
  "type": "record",
  "namespace": "Energistics.Etp.v12.Datatypes",
  "name": "ErrorInfo",
  "fields":
  [
	{ "name": "message", "type": "string", "default": "" },
	{ "name": "code", "type": "int", "default": 0 }
  ]
}
```

**Comment by markfarnan** [comment]
Ah, I see. 

Ok, that won't work then, as can't change the Schemas.  

As these fields are not 'nullable' (not union of nulls and something) anyway,  what would be the point of having a default for null, given it should never occur ?

**Comment by markfarnan** [comment]
Understood.     Not an issue than, can nuke / close this/
