### ISSUE TITLE
upstream apache-avro

### ISSUE THREAD

**Issue by untereiner** [lerouxrgd/rsgen-avro#46]
Would it be possible to have a develop branch and a CI able to point to the upstream version of the apache-avro crate ?

**Comment by lerouxrgd** [comment]
What would be the benefit of such a setup ? Right now this crate is updated when a new version of `apache-avro` is published.

**Comment by untereiner** [comment]
apache-avro has a long running official update rythm. The benefit would be to have access in rsgen-avro to the latest work in apache-avro.

**Comment by martin-g** [comment]
https://lists.apache.org/thread/2rfnszd4dk36jxynpj382b1717gbyv1y

**Comment by lerouxrgd** [comment]
This logic was implemented for apache-avro 0.17 using a dedicated branch until it was released.
The same strategy will be used for future apache-avro versions, on an as-needed basis.
