### ISSUE TITLE
Templating error: Io error while writing rendered value to output: NotADirectory

### ISSUE THREAD

**Issue by dario-davi** [lerouxrgd/rsgen-avro#49]
Hi,

whene I run the following command
`./.cargo/bin/rsgen-avro ./RawResponse_1.json -`
I get the following error
`Templating error: Io error while writing rendered value to output: NotADirectory`

My Avro schemma is preatty long, if you need I can link it, but it seems a problem with paths, not with schema content.

Thanks,
Dario

**Comment by lerouxrgd** [comment]
Hello, I think `./RawResponse_1.json` is interpreted as a directory.

Could you try like that:

```
./.cargo/bin/rsgen-avro RawResponse_1.json -
```

**Comment by lerouxrgd** [comment]
Thank you for the schema.

First of all you need to change a bit the structure for it to be valid. Currently you have something like this:

```json
{
  "schema" : {},
  "schemaType" : "AVRO",
  "references" : [ ]
}
```

But you have to extract only the `"schema"` part and put it in a file, so that the content is like this:

```json
{
    "type" : "record",
    "name" : "RawResponseToUploadDtoV1d0",
    "namespace" : "com.enel.sb.ms.normalizer.dto.events.output",
    [...]
}
```

With this correct schema I gave it a try with the latest `rsgen-avro` which is 0.11.8 (downloaded from the [release page](https://github.com/lerouxrgd/rsgen-avro/releases)) :

```
rsgen-avro schema.avsc -
```

But it fails with:

```
thread 'main' panicked at 'Ref `Name { name: "RegisterValueDto", namespace: None }` is not resolved. Schema: Ref { name: Name { name: "RegisterValueDto", namespace: None } }', src/templates.rs:298:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I will investigate it further ...

**Comment by dario-davi** [comment]
Ok thanks

**Comment by lerouxrgd** [comment]
I have released version `0.11.9` that you can download from the [release page](https://github.com/lerouxrgd/rsgen-avro/releases/tag/0.11.9) that fixes the issues you encountered.

However there is 1 change required to your schema. When you use `RegisterValueDto` as a value in a map you currently have:

```json
{
  "type" : "map",
  "values" : "RegisterValueDto"
}
```

But for `rsgen-avro` to work you need to write its fully-qualified name as follows:

```json
{
  "type" : "map",
  "values" : "com.enel.sb.ms.normalizer.dto.events.output.common.RegisterValueDto"
}
```

Let me know if that works for you.

**Comment by dario-davi** [comment]
OK ,thank you very much, I will try!
The only strange thing is that I generate that avro schema from existing java classes using avro official java library: it's very strange that it creates an out of standard schema.

**Comment by lerouxrgd** [comment]
The schema is standard as is (I tried to use it to generate some random data in avro format).
But for [apache-avro](https://crates.io/crates/apache-avro) in Rust to parse the schema correctly it seems necessary to have fully-qualified names here.

**Comment by dario-davi** [comment]
Hi, I think it's working correctly, thanks
