### ISSUE TITLE
Generated file content is a subset of Avro schema content

### ISSUE THREAD

**Issue by dario-davi** [lerouxrgd/rsgen-avro#52]
Hi,

I have the following schema: [https://pastebin.com/0E89tzsS](https://pastebin.com/0E89tzsS) but rsavro-gen generates a file with much less fields and structs: [https://pastebin.com/qeXDzw2v](https://pastebin.com/qeXDzw2v) .

thank you very much

**Comment by lerouxrgd** [comment]
If I run it I have the error:

```
Templating error: Didn't find schema Map(Record { name: Name { name: "Object", namespace: Some("java.lang") }
```

This is usable only from Java.

**Comment by lerouxrgd** [comment]
Closing this as this is Java specific. Don't hesitate to re-open if you have a similar issue with a Java-independent schema.
