### ISSUE TITLE
Any Plans to Support the IDL?

### ISSUE THREAD

**Issue by baxterjo** [lerouxrgd/rsgen-avro#72]
Not an issue, but are there any plans to support IDL files? IDL files are much more ergonomic than the schemas, but converting from .avdl to .avsc using another language is pretty cumbersome as well.

**Comment by mati865** [comment]
related: https://github.com/lerouxrgd/rsgen-avro/pull/56

**Comment by lerouxrgd** [comment]
Indeed, as discussed in PR #56 you can give [avdl-rs](https://github.com/woile/avdl-rs) a try. I have no plan to support Avro IDL in this crate, I think it should be part of `apache-avro` in order to give you a `Schema` which is the abstraction this crate is based on.
