### ISSUE TITLE
Cannot generate an Optional array

### ISSUE THREAD

**Issue by colinbankier** [lerouxrgd/rsgen-avro#8]
A schema with the following field fails to generate rust code:
```
    {
      "name": "GROUP_NAMES",
      "type": [
        "null",
        {
          "type": "array",
          "items": [
            "null",
            "string"
          ]
        }
      ],
      "default": null
    }
```
with the error

> Problem during code generation: Templating error: Didn't find schema Array(Union(UnionSchema { schemas: [Null, String], variant_index: {Null: 0, String: 1} })) in state GenState({4431444975918093497: "Vec<Option<String>>", 2318155486020329502: "Option<String>"})

Given optional fields are handled elsewhere, I would expect this to generate a field of type:
```
Option<Vec<Option<String>>>
```

This came up trying to use a schema generated by ksqlDB - in a ksqlDB stream all fields are optional, and this is the schema it outputs for an `ARRAY<VARCHAR(STRING)>` field.

**Comment by lerouxrgd** [comment]
Thank you for the report, that's an interesting edge case.

I think the generation process gets confused because this is not part of an Avro `record`. I mean the result can't live by itself in Rust (it would at least need to be aliased with something like `type GroupNames = Option<Vec<Option<String>>>`).

So if this type is part of a bigger `record` schema, I think this should be fine. Isn't it the case if what you're describing with the schema is a `record` where this `GROUP_NAMES` would be a single field ?

**Comment by lerouxrgd** [comment]
Sorry I read too fast and didn't see you mentioned that this is a field of a record already.

Can you provide a similar Avro schema so that I can reproduce the error you are seeing ?

**Comment by colinbankier** [comment]
Ok, Interesting - thanks for your response. I found it fails if there is more than 1 field with this type:
```
{
  "type": "record",
  "name": "KsqlDataSourceSchema",
  "namespace": "io.confluent.ksql.avro_schemas",
  "fields": [
    {
      "name": "ID",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "GROUP_IDS",
      "type": [
        "null",
        {
          "type": "array",
          "items": [
            "null",
            "string"
          ]
        }
      ],
      "default": null
    },
    {
      "name": "GROUP_NAMES",
      "type": [
        "null",
        {
          "type": "array",
          "items": [
            "null",
            "string"
          ]
        }
      ],
      "default": null
    }
  ]
}

```

**Comment by lerouxrgd** [comment]
Thank you for narrowing it down.

I publish `0.7.1` which should fix it, let me know how it goes.

**Comment by colinbankier** [comment]
Perfect - thanks! It handles that case perfectly now 👍
